name: Release Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

#     - name: Test
#       run: go test -v .

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: android-app-publisher

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: android-app-publisher
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
